[package]
name = "ieee802_3_mii"
version = "0.2.0-ALPHA1"
edition = "2021"
authors = ["Johannes Cornelis Draaijer <jcdra1@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "An IEEE 802.3 MII trait, providing access to registers defined in the standard and default implementations for common PHYs"
homepage = "https://github.com/datdenkikniet/ieee802_3_mii"
keywords = ["ethernet"]
categories = ["embedded", "no-std", "hardware-support"]
readme = "README.md"

[features]
default = [ "lan87xxa", "kzs8081r" ]

phy = [ ]
lan87xxa = [ "phy" ]
kzs8081r = [ "phy" ]

[dependencies]
bitflags = "1.3"
