[package]
name = "ieee802_3_mii"
version = "0.1.0"
edition = "2021"
authors = ["Johannes Cornelis Draaijer <jcdra1@gmail.com>"]
license = "MIT OR Apache-2.0"
license-file = "LICENSE"
description = "An IEEE 802.3 MII trait, providing access to registers defined in the standard and default implementations for common PHYs"
homepage = "https://github.com/datdenkikniet/ieee802_3_mii"
keywords = ["IEEE 802.3", "ethernet", "Media Independent Interface"]
categories = ["embedded", "no-std", "ethernet"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
